pub struct TeamTemplate {
    pub nome: &'static str,
    pub nome_curto: &'static str,
    pub categoria: &'static str,
    pub cor_primaria: &'static str,
    pub cor_secundaria: &'static str,
    pub pais_sede: &'static str,
    pub marca: Option<&'static str>,
    pub classe: Option<&'static str>,
    pub car_performance_base: f64,
    pub budget_base: f64,
    pub reputacao_base: f64,
}

static TEAMS: &[TeamTemplate] = &[
    TeamTemplate {
        nome: "Racing Academy Red",
        nome_curto: "RAR",
        categoria: "mazda_rookie",
        cor_primaria: "#cc0000",
        cor_secundaria: "#ffffff",
        pais_sede: "🇺🇸 EUA",
        marca: None,
        classe: None,
        car_performance_base: 1.0,
        budget_base: 22.0,
        reputacao_base: 18.0,
    },
    TeamTemplate {
        nome: "Rolling Thunder Academy",
        nome_curto: "RTA",
        categoria: "mazda_rookie",
        cor_primaria: "#1a1a2e",
        cor_secundaria: "#e94560",
        pais_sede: "🇺🇸 EUA",
        marca: None,
        classe: None,
        car_performance_base: 2.0,
        budget_base: 25.0,
        reputacao_base: 20.0,
    },
    TeamTemplate {
        nome: "Grid Start Racing School",
        nome_curto: "GSR",
        categoria: "mazda_rookie",
        cor_primaria: "#ff6b00",
        cor_secundaria: "#000000",
        pais_sede: "🇬🇧 Reino Unido",
        marca: None,
        classe: None,
        car_performance_base: 0.0,
        budget_base: 20.0,
        reputacao_base: 15.0,
    },
    TeamTemplate {
        nome: "First Gear Motorsport",
        nome_curto: "FGM",
        categoria: "mazda_rookie",
        cor_primaria: "#00457c",
        cor_secundaria: "#f0f0f0",
        pais_sede: "🇩🇪 Alemanha",
        marca: None,
        classe: None,
        car_performance_base: 1.5,
        budget_base: 23.0,
        reputacao_base: 17.0,
    },
    TeamTemplate {
        nome: "Apex Academy Racing",
        nome_curto: "AAR",
        categoria: "mazda_rookie",
        cor_primaria: "#2d6a4f",
        cor_secundaria: "#ffffff",
        pais_sede: "🇫🇷 França",
        marca: None,
        classe: None,
        car_performance_base: 2.5,
        budget_base: 28.0,
        reputacao_base: 22.0,
    },
    TeamTemplate {
        nome: "Rookie Squad Racing",
        nome_curto: "RSQ",
        categoria: "mazda_rookie",
        cor_primaria: "#7b2d8b",
        cor_secundaria: "#e0e0e0",
        pais_sede: "🇯🇵 Japão",
        marca: None,
        classe: None,
        car_performance_base: 0.5,
        budget_base: 21.0,
        reputacao_base: 16.0,
    },
    TeamTemplate {
        nome: "TRD Driver Academy",
        nome_curto: "TDA",
        categoria: "toyota_rookie",
        cor_primaria: "#eb0a1e",
        cor_secundaria: "#ffffff",
        pais_sede: "🇯🇵 Japão",
        marca: None,
        classe: None,
        car_performance_base: 2.0,
        budget_base: 27.0,
        reputacao_base: 22.0,
    },
    TeamTemplate {
        nome: "GR Racing School",
        nome_curto: "GRS",
        categoria: "toyota_rookie",
        cor_primaria: "#1c3557",
        cor_secundaria: "#c8a84b",
        pais_sede: "🇯🇵 Japão",
        marca: None,
        classe: None,
        car_performance_base: 2.5,
        budget_base: 29.0,
        reputacao_base: 25.0,
    },
    TeamTemplate {
        nome: "Open Road Academy",
        nome_curto: "ORA",
        categoria: "toyota_rookie",
        cor_primaria: "#0b5563",
        cor_secundaria: "#ffffff",
        pais_sede: "🇺🇸 EUA",
        marca: None,
        classe: None,
        car_performance_base: 0.5,
        budget_base: 21.0,
        reputacao_base: 16.0,
    },
    TeamTemplate {
        nome: "Speed Lab Rookies",
        nome_curto: "SLR",
        categoria: "toyota_rookie",
        cor_primaria: "#ff4500",
        cor_secundaria: "#111111",
        pais_sede: "🇺🇸 EUA",
        marca: None,
        classe: None,
        car_performance_base: 1.0,
        budget_base: 22.0,
        reputacao_base: 18.0,
    },
    TeamTemplate {
        nome: "Rising Stars Motorsport",
        nome_curto: "RSM",
        categoria: "toyota_rookie",
        cor_primaria: "#ffd700",
        cor_secundaria: "#333333",
        pais_sede: "🇬🇧 Reino Unido",
        marca: None,
        classe: None,
        car_performance_base: 1.5,
        budget_base: 24.0,
        reputacao_base: 20.0,
    },
    TeamTemplate {
        nome: "Fresh Start Racing",
        nome_curto: "FSR",
        categoria: "toyota_rookie",
        cor_primaria: "#228b22",
        cor_secundaria: "#ffffff",
        pais_sede: "🇩🇪 Alemanha",
        marca: None,
        classe: None,
        car_performance_base: 0.0,
        budget_base: 20.0,
        reputacao_base: 15.0,
    },
    TeamTemplate {
        nome: "MX5 Touring Club",
        nome_curto: "MTC",
        categoria: "mazda_amador",
        cor_primaria: "#cc0000",
        cor_secundaria: "#ffffff",
        pais_sede: "🇺🇸 EUA",
        marca: None,
        classe: None,
        car_performance_base: 4.0,
        budget_base: 42.0,
        reputacao_base: 38.0,
    },
    TeamTemplate {
        nome: "Weekend Warriors Racing",
        nome_curto: "WWR",
        categoria: "mazda_amador",
        cor_primaria: "#2c3e50",
        cor_secundaria: "#e74c3c",
        pais_sede: "🇺🇸 EUA",
        marca: None,
        classe: None,
        car_performance_base: 2.0,
        budget_base: 33.0,
        reputacao_base: 28.0,
    },
    TeamTemplate {
        nome: "Club Racer Motorsport",
        nome_curto: "CRM",
        categoria: "mazda_amador",
        cor_primaria: "#16a085",
        cor_secundaria: "#ffffff",
        pais_sede: "🇬🇧 Reino Unido",
        marca: None,
        classe: None,
        car_performance_base: 3.0,
        budget_base: 38.0,
        reputacao_base: 33.0,
    },
    TeamTemplate {
        nome: "Dual Exit Racing",
        nome_curto: "DER",
        categoria: "mazda_amador",
        cor_primaria: "#8e44ad",
        cor_secundaria: "#f1c40f",
        pais_sede: "🇩🇪 Alemanha",
        marca: None,
        classe: None,
        car_performance_base: 5.0,
        budget_base: 50.0,
        reputacao_base: 45.0,
    },
    TeamTemplate {
        nome: "Sunday Speed Club",
        nome_curto: "SSC",
        categoria: "mazda_amador",
        cor_primaria: "#d35400",
        cor_secundaria: "#ecf0f1",
        pais_sede: "🇫🇷 França",
        marca: None,
        classe: None,
        car_performance_base: 1.5,
        budget_base: 30.0,
        reputacao_base: 25.0,
    },
    TeamTemplate {
        nome: "Grassroots Racing Team",
        nome_curto: "GRT",
        categoria: "mazda_amador",
        cor_primaria: "#27ae60",
        cor_secundaria: "#2c3e50",
        pais_sede: "🇺🇸 EUA",
        marca: None,
        classe: None,
        car_performance_base: 2.5,
        budget_base: 35.0,
        reputacao_base: 30.0,
    },
    TeamTemplate {
        nome: "Petrolhead United",
        nome_curto: "PHU",
        categoria: "mazda_amador",
        cor_primaria: "#c0392b",
        cor_secundaria: "#f39c12",
        pais_sede: "🇬🇧 Reino Unido",
        marca: None,
        classe: None,
        car_performance_base: 3.5,
        budget_base: 40.0,
        reputacao_base: 35.0,
    },
    TeamTemplate {
        nome: "Track Day Heroes",
        nome_curto: "TDH",
        categoria: "mazda_amador",
        cor_primaria: "#1abc9c",
        cor_secundaria: "#2c3e50",
        pais_sede: "🇳🇱 Holanda",
        marca: None,
        classe: None,
        car_performance_base: 1.0,
        budget_base: 31.0,
        reputacao_base: 26.0,
    },
    TeamTemplate {
        nome: "Late Apex Contenders",
        nome_curto: "LAC",
        categoria: "mazda_amador",
        cor_primaria: "#2980b9",
        cor_secundaria: "#ffffff",
        pais_sede: "🇯🇵 Japão",
        marca: None,
        classe: None,
        car_performance_base: 4.5,
        budget_base: 47.0,
        reputacao_base: 42.0,
    },
    TeamTemplate {
        nome: "Amateur Hour Racing",
        nome_curto: "AHR",
        categoria: "mazda_amador",
        cor_primaria: "#7f8c8d",
        cor_secundaria: "#ecf0f1",
        pais_sede: "🇺🇸 EUA",
        marca: None,
        classe: None,
        car_performance_base: 1.0,
        budget_base: 32.0,
        reputacao_base: 27.0,
    },
    TeamTemplate {
        nome: "GR86 Cup Racing",
        nome_curto: "GCR",
        categoria: "toyota_amador",
        cor_primaria: "#eb0a1e",
        cor_secundaria: "#f0f0f0",
        pais_sede: "🇯🇵 Japão",
        marca: None,
        classe: None,
        car_performance_base: 4.5,
        budget_base: 48.0,
        reputacao_base: 43.0,
    },
    TeamTemplate {
        nome: "Street to Track Team",
        nome_curto: "STT",
        categoria: "toyota_amador",
        cor_primaria: "#2e4057",
        cor_secundaria: "#ffffff",
        pais_sede: "🇺🇸 EUA",
        marca: None,
        classe: None,
        car_performance_base: 2.0,
        budget_base: 34.0,
        reputacao_base: 29.0,
    },
    TeamTemplate {
        nome: "Flat Six Motorsport",
        nome_curto: "FSM",
        categoria: "toyota_amador",
        cor_primaria: "#e67e22",
        cor_secundaria: "#111111",
        pais_sede: "🇩🇪 Alemanha",
        marca: None,
        classe: None,
        car_performance_base: 3.0,
        budget_base: 39.0,
        reputacao_base: 34.0,
    },
    TeamTemplate {
        nome: "Gentleman Driver Club",
        nome_curto: "GDC",
        categoria: "toyota_amador",
        cor_primaria: "#6c5ce7",
        cor_secundaria: "#dfe6e9",
        pais_sede: "🇧🇪 Bélgica",
        marca: None,
        classe: None,
        car_performance_base: 5.0,
        budget_base: 52.0,
        reputacao_base: 47.0,
    },
    TeamTemplate {
        nome: "Toyota Cup Challenge",
        nome_curto: "TCC",
        categoria: "toyota_amador",
        cor_primaria: "#eb0a1e",
        cor_secundaria: "#333333",
        pais_sede: "🇯🇵 Japão",
        marca: None,
        classe: None,
        car_performance_base: 3.5,
        budget_base: 43.0,
        reputacao_base: 38.0,
    },
    TeamTemplate {
        nome: "Rev Happy Racing",
        nome_curto: "RHR",
        categoria: "toyota_amador",
        cor_primaria: "#00b894",
        cor_secundaria: "#2d3436",
        pais_sede: "🇦🇺 Austrália",
        marca: None,
        classe: None,
        car_performance_base: 2.5,
        budget_base: 36.0,
        reputacao_base: 31.0,
    },
    TeamTemplate {
        nome: "Corner Workers Racing",
        nome_curto: "CWR",
        categoria: "toyota_amador",
        cor_primaria: "#fdcb6e",
        cor_secundaria: "#2d3436",
        pais_sede: "🇺🇸 EUA",
        marca: None,
        classe: None,
        car_performance_base: 1.5,
        budget_base: 31.0,
        reputacao_base: 26.0,
    },
    TeamTemplate {
        nome: "Daily Driver Racing",
        nome_curto: "DDR",
        categoria: "toyota_amador",
        cor_primaria: "#74b9ff",
        cor_secundaria: "#2d3436",
        pais_sede: "🇬🇧 Reino Unido",
        marca: None,
        classe: None,
        car_performance_base: 1.0,
        budget_base: 30.0,
        reputacao_base: 25.0,
    },
    TeamTemplate {
        nome: "Smooth Line Motorsport",
        nome_curto: "SLM",
        categoria: "toyota_amador",
        cor_primaria: "#0984e3",
        cor_secundaria: "#ffffff",
        pais_sede: "🇫🇷 França",
        marca: None,
        classe: None,
        car_performance_base: 4.0,
        budget_base: 45.0,
        reputacao_base: 40.0,
    },
    TeamTemplate {
        nome: "Over the Limit Racing",
        nome_curto: "OTL",
        categoria: "toyota_amador",
        cor_primaria: "#d63031",
        cor_secundaria: "#636e72",
        pais_sede: "🇳🇱 Holanda",
        marca: None,
        classe: None,
        car_performance_base: 2.0,
        budget_base: 33.0,
        reputacao_base: 28.0,
    },
    TeamTemplate {
        nome: "Bayern Racing Division",
        nome_curto: "BRD",
        categoria: "bmw_m2",
        cor_primaria: "#0066cc",
        cor_secundaria: "#ffffff",
        pais_sede: "🇩🇪 Alemanha",
        marca: None,
        classe: None,
        car_performance_base: 7.0,
        budget_base: 58.0,
        reputacao_base: 54.0,
    },
    TeamTemplate {
        nome: "M Power Motorsport",
        nome_curto: "MPM",
        categoria: "bmw_m2",
        cor_primaria: "#1c1c1c",
        cor_secundaria: "#0066cc",
        pais_sede: "🇩🇪 Alemanha",
        marca: None,
        classe: None,
        car_performance_base: 6.0,
        budget_base: 52.0,
        reputacao_base: 48.0,
    },
    TeamTemplate {
        nome: "Blue Propeller Racing",
        nome_curto: "BPR",
        categoria: "bmw_m2",
        cor_primaria: "#003c80",
        cor_secundaria: "#e8e8e8",
        pais_sede: "🇬🇧 Reino Unido",
        marca: None,
        classe: None,
        car_performance_base: 5.0,
        budget_base: 46.0,
        reputacao_base: 42.0,
    },
    TeamTemplate {
        nome: "Munich Speed Works",
        nome_curto: "MSW",
        categoria: "bmw_m2",
        cor_primaria: "#c0c0c0",
        cor_secundaria: "#0066cc",
        pais_sede: "🇩🇪 Alemanha",
        marca: None,
        classe: None,
        car_performance_base: 7.5,
        budget_base: 60.0,
        reputacao_base: 56.0,
    },
    TeamTemplate {
        nome: "Bavarian Track Team",
        nome_curto: "BTT",
        categoria: "bmw_m2",
        cor_primaria: "#ffffff",
        cor_secundaria: "#0066cc",
        pais_sede: "🇩🇪 Alemanha",
        marca: None,
        classe: None,
        car_performance_base: 3.0,
        budget_base: 38.0,
        reputacao_base: 34.0,
    },
    TeamTemplate {
        nome: "M2 Sport Racing",
        nome_curto: "M2S",
        categoria: "bmw_m2",
        cor_primaria: "#1a1a2e",
        cor_secundaria: "#e94560",
        pais_sede: "🇫🇷 França",
        marca: None,
        classe: None,
        car_performance_base: 4.5,
        budget_base: 44.0,
        reputacao_base: 40.0,
    },
    TeamTemplate {
        nome: "Corporate Express Racing",
        nome_curto: "CER",
        categoria: "bmw_m2",
        cor_primaria: "#f0f0f0",
        cor_secundaria: "#333333",
        pais_sede: "🇨🇭 Suíça",
        marca: None,
        classe: None,
        car_performance_base: 2.5,
        budget_base: 36.0,
        reputacao_base: 32.0,
    },
    TeamTemplate {
        nome: "Roundel Motorsport",
        nome_curto: "RML",
        categoria: "bmw_m2",
        cor_primaria: "#ffd700",
        cor_secundaria: "#003c80",
        pais_sede: "🇬🇧 Reino Unido",
        marca: None,
        classe: None,
        car_performance_base: 6.5,
        budget_base: 55.0,
        reputacao_base: 51.0,
    },
    TeamTemplate {
        nome: "Precision Drive Racing",
        nome_curto: "PDR",
        categoria: "bmw_m2",
        cor_primaria: "#e74c3c",
        cor_secundaria: "#2c3e50",
        pais_sede: "🇦🇺 Austrália",
        marca: None,
        classe: None,
        car_performance_base: 4.0,
        budget_base: 42.0,
        reputacao_base: 38.0,
    },
    TeamTemplate {
        nome: "German Precision Racing",
        nome_curto: "GPR",
        categoria: "bmw_m2",
        cor_primaria: "#2c3e50",
        cor_secundaria: "#bdc3c7",
        pais_sede: "🇩🇪 Alemanha",
        marca: None,
        classe: None,
        car_performance_base: 3.5,
        budget_base: 40.0,
        reputacao_base: 36.0,
    },
    TeamTemplate {
        nome: "Pro Mazda Challenge",
        nome_curto: "PMC",
        categoria: "production_challenger",
        cor_primaria: "#cc0000",
        cor_secundaria: "#ffffff",
        pais_sede: "🇺🇸 EUA",
        marca: Some("Mazda"),
        classe: Some("mazda"),
        car_performance_base: 4.0,
        budget_base: 42.0,
        reputacao_base: 37.0,
    },
    TeamTemplate {
        nome: "MX5 Masters Racing",
        nome_curto: "MMR",
        categoria: "production_challenger",
        cor_primaria: "#1a1a2e",
        cor_secundaria: "#cc0000",
        pais_sede: "🇺🇸 EUA",
        marca: Some("Mazda"),
        classe: Some("mazda"),
        car_performance_base: 5.5,
        budget_base: 50.0,
        reputacao_base: 46.0,
    },
    TeamTemplate {
        nome: "Mazda Racer Cup",
        nome_curto: "MRC",
        categoria: "production_challenger",
        cor_primaria: "#2980b9",
        cor_secundaria: "#cc0000",
        pais_sede: "🇯🇵 Japão",
        marca: Some("Mazda"),
        classe: Some("mazda"),
        car_performance_base: 3.0,
        budget_base: 36.0,
        reputacao_base: 31.0,
    },
    TeamTemplate {
        nome: "Winning Run Racing",
        nome_curto: "WRR",
        categoria: "production_challenger",
        cor_primaria: "#f39c12",
        cor_secundaria: "#2c3e50",
        pais_sede: "🇬🇧 Reino Unido",
        marca: Some("Mazda"),
        classe: Some("mazda"),
        car_performance_base: 6.0,
        budget_base: 54.0,
        reputacao_base: 49.0,
    },
    TeamTemplate {
        nome: "Turning Wheel Motorsport",
        nome_curto: "TWM",
        categoria: "production_challenger",
        cor_primaria: "#27ae60",
        cor_secundaria: "#ecf0f1",
        pais_sede: "🇩🇪 Alemanha",
        marca: Some("Mazda"),
        classe: Some("mazda"),
        car_performance_base: 2.5,
        budget_base: 33.0,
        reputacao_base: 28.0,
    },
    TeamTemplate {
        nome: "GR Cup Elite",
        nome_curto: "GCE",
        categoria: "production_challenger",
        cor_primaria: "#eb0a1e",
        cor_secundaria: "#1c3557",
        pais_sede: "🇯🇵 Japão",
        marca: Some("Toyota"),
        classe: Some("toyota"),
        car_performance_base: 5.5,
        budget_base: 52.0,
        reputacao_base: 47.0,
    },
    TeamTemplate {
        nome: "Toyota Racing Series",
        nome_curto: "TRS",
        categoria: "production_challenger",
        cor_primaria: "#eb0a1e",
        cor_secundaria: "#ffffff",
        pais_sede: "🇳🇿 Nova Zelândia",
        marca: Some("Toyota"),
        classe: Some("toyota"),
        car_performance_base: 6.5,
        budget_base: 60.0,
        reputacao_base: 55.0,
    },
    TeamTemplate {
        nome: "Apex Toyota Club",
        nome_curto: "ATC",
        categoria: "production_challenger",
        cor_primaria: "#2d3436",
        cor_secundaria: "#eb0a1e",
        pais_sede: "🇦🇺 Austrália",
        marca: Some("Toyota"),
        classe: Some("toyota"),
        car_performance_base: 3.5,
        budget_base: 40.0,
        reputacao_base: 35.0,
    },
    TeamTemplate {
        nome: "Six Star Racing",
        nome_curto: "SSR",
        categoria: "production_challenger",
        cor_primaria: "#0984e3",
        cor_secundaria: "#fdcb6e",
        pais_sede: "🇺🇸 EUA",
        marca: Some("Toyota"),
        classe: Some("toyota"),
        car_performance_base: 4.5,
        budget_base: 46.0,
        reputacao_base: 41.0,
    },
    TeamTemplate {
        nome: "Far East Speed",
        nome_curto: "FES",
        categoria: "production_challenger",
        cor_primaria: "#a29bfe",
        cor_secundaria: "#2d3436",
        pais_sede: "🇯🇵 Japão",
        marca: Some("Toyota"),
        classe: Some("toyota"),
        car_performance_base: 2.5,
        budget_base: 34.0,
        reputacao_base: 29.0,
    },
    TeamTemplate {
        nome: "M2 Masters Racing",
        nome_curto: "M2M",
        categoria: "production_challenger",
        cor_primaria: "#0066cc",
        cor_secundaria: "#c0c0c0",
        pais_sede: "🇩🇪 Alemanha",
        marca: Some("BMW"),
        classe: Some("bmw"),
        car_performance_base: 6.0,
        budget_base: 56.0,
        reputacao_base: 51.0,
    },
    TeamTemplate {
        nome: "BMW Club Racing",
        nome_curto: "BCR",
        categoria: "production_challenger",
        cor_primaria: "#ffffff",
        cor_secundaria: "#0066cc",
        pais_sede: "🇩🇪 Alemanha",
        marca: Some("BMW"),
        classe: Some("bmw"),
        car_performance_base: 4.0,
        budget_base: 44.0,
        reputacao_base: 39.0,
    },
    TeamTemplate {
        nome: "Sharp Corner Racing",
        nome_curto: "SCR",
        categoria: "production_challenger",
        cor_primaria: "#e17055",
        cor_secundaria: "#2d3436",
        pais_sede: "🇬🇧 Reino Unido",
        marca: Some("BMW"),
        classe: Some("bmw"),
        car_performance_base: 5.0,
        budget_base: 48.0,
        reputacao_base: 43.0,
    },
    TeamTemplate {
        nome: "White Black Motorsport",
        nome_curto: "WBM",
        categoria: "production_challenger",
        cor_primaria: "#dfe6e9",
        cor_secundaria: "#2d3436",
        pais_sede: "🇨🇭 Suíça",
        marca: Some("BMW"),
        classe: Some("bmw"),
        car_performance_base: 3.0,
        budget_base: 38.0,
        reputacao_base: 33.0,
    },
    TeamTemplate {
        nome: "Alpine Express BMW",
        nome_curto: "AEB",
        categoria: "production_challenger",
        cor_primaria: "#003c80",
        cor_secundaria: "#ffd700",
        pais_sede: "🇦🇹 Áustria",
        marca: Some("BMW"),
        classe: Some("bmw"),
        car_performance_base: 7.0,
        budget_base: 62.0,
        reputacao_base: 57.0,
    },
    TeamTemplate {
        nome: "Team RLL Racing",
        nome_curto: "RLL",
        categoria: "gt4",
        cor_primaria: "#003c80",
        cor_secundaria: "#ffd700",
        pais_sede: "🇺🇸 EUA",
        marca: Some("BMW"),
        classe: None,
        car_performance_base: 8.0,
        budget_base: 62.0,
        reputacao_base: 57.0,
    },
    TeamTemplate {
        nome: "Toksport WRT",
        nome_curto: "TWR",
        categoria: "gt4",
        cor_primaria: "#c0392b",
        cor_secundaria: "#f0f0f0",
        pais_sede: "🇩🇪 Alemanha",
        marca: Some("BMW"),
        classe: None,
        car_performance_base: 5.0,
        budget_base: 50.0,
        reputacao_base: 46.0,
    },
    TeamTemplate {
        nome: "SRO Motorsport Academy",
        nome_curto: "SRO",
        categoria: "gt4",
        cor_primaria: "#1c1c1c",
        cor_secundaria: "#f39c12",
        pais_sede: "🇬🇧 Reino Unido",
        marca: Some("Porsche"),
        classe: None,
        car_performance_base: 9.0,
        budget_base: 67.0,
        reputacao_base: 62.0,
    },
    TeamTemplate {
        nome: "G-Drive Racing",
        nome_curto: "GDR",
        categoria: "gt4",
        cor_primaria: "#f39c12",
        cor_secundaria: "#2c3e50",
        pais_sede: "🇫🇷 França",
        marca: Some("Porsche"),
        classe: None,
        car_performance_base: 6.0,
        budget_base: 53.0,
        reputacao_base: 49.0,
    },
    TeamTemplate {
        nome: "HubAuto Corsa",
        nome_curto: "HUB",
        categoria: "gt4",
        cor_primaria: "#c8a84b",
        cor_secundaria: "#1c1c1c",
        pais_sede: "🇹🇼 Taiwan",
        marca: Some("Mercedes-AMG"),
        classe: None,
        car_performance_base: 7.0,
        budget_base: 58.0,
        reputacao_base: 53.0,
    },
    TeamTemplate {
        nome: "SPS Automotive Performance",
        nome_curto: "SPS",
        categoria: "gt4",
        cor_primaria: "#2c3e50",
        cor_secundaria: "#c0c0c0",
        pais_sede: "🇩🇪 Alemanha",
        marca: Some("Mercedes-AMG"),
        classe: None,
        car_performance_base: 4.0,
        budget_base: 44.0,
        reputacao_base: 40.0,
    },
    TeamTemplate {
        nome: "Heart of Racing GT4",
        nome_curto: "HOR4",
        categoria: "gt4",
        cor_primaria: "#c0392b",
        cor_secundaria: "#2c3e50",
        pais_sede: "🇺🇸 EUA",
        marca: Some("Aston Martin"),
        classe: None,
        car_performance_base: 9.5,
        budget_base: 69.0,
        reputacao_base: 64.0,
    },
    TeamTemplate {
        nome: "Balfe Motorsport",
        nome_curto: "BLF",
        categoria: "gt4",
        cor_primaria: "#000080",
        cor_secundaria: "#ff8c00",
        pais_sede: "🇬🇧 Reino Unido",
        marca: Some("McLaren"),
        classe: None,
        car_performance_base: 7.5,
        budget_base: 61.0,
        reputacao_base: 56.0,
    },
    TeamTemplate {
        nome: "Aures Racing",
        nome_curto: "ARS",
        categoria: "gt4",
        cor_primaria: "#ff8c00",
        cor_secundaria: "#2c3e50",
        pais_sede: "🇫🇷 França",
        marca: Some("McLaren"),
        classe: None,
        car_performance_base: 3.5,
        budget_base: 42.0,
        reputacao_base: 38.0,
    },
    TeamTemplate {
        nome: "GR Racing GT4",
        nome_curto: "GRR4",
        categoria: "gt4",
        cor_primaria: "#eb0a1e",
        cor_secundaria: "#ffffff",
        pais_sede: "🇬🇧 Reino Unido",
        marca: Some("Toyota"),
        classe: None,
        car_performance_base: 6.0,
        budget_base: 54.0,
        reputacao_base: 50.0,
    },
    TeamTemplate {
        nome: "SunEnergy1 Racing",
        nome_curto: "SEN",
        categoria: "gt3",
        cor_primaria: "#ffcc00",
        cor_secundaria: "#1a1a1a",
        pais_sede: "🇺🇸 EUA",
        marca: Some("Mercedes-AMG"),
        classe: None,
        car_performance_base: 15.0,
        budget_base: 83.0,
        reputacao_base: 87.0,
    },
    TeamTemplate {
        nome: "Paul Miller Racing",
        nome_curto: "PMR",
        categoria: "gt3",
        cor_primaria: "#ffd700",
        cor_secundaria: "#1a1a1a",
        pais_sede: "🇺🇸 EUA",
        marca: Some("Lamborghini"),
        classe: None,
        car_performance_base: 14.0,
        budget_base: 80.0,
        reputacao_base: 84.0,
    },
    TeamTemplate {
        nome: "Wright Motorsports",
        nome_curto: "WMS",
        categoria: "gt3",
        cor_primaria: "#ff8c00",
        cor_secundaria: "#000000",
        pais_sede: "🇺🇸 EUA",
        marca: Some("Porsche"),
        classe: None,
        car_performance_base: 13.0,
        budget_base: 77.0,
        reputacao_base: 81.0,
    },
    TeamTemplate {
        nome: "Heart of Racing GT3",
        nome_curto: "HOR",
        categoria: "gt3",
        cor_primaria: "#c0392b",
        cor_secundaria: "#2c3e50",
        pais_sede: "🇺🇸 EUA",
        marca: Some("Aston Martin"),
        classe: None,
        car_performance_base: 11.0,
        budget_base: 72.0,
        reputacao_base: 75.0,
    },
    TeamTemplate {
        nome: "K-PAX Racing",
        nome_curto: "KPX",
        categoria: "gt3",
        cor_primaria: "#00695c",
        cor_secundaria: "#ffffff",
        pais_sede: "🇺🇸 EUA",
        marca: Some("McLaren"),
        classe: None,
        car_performance_base: 10.5,
        budget_base: 70.0,
        reputacao_base: 73.0,
    },
    TeamTemplate {
        nome: "Team Korthoff Motorsports",
        nome_curto: "TKM",
        categoria: "gt3",
        cor_primaria: "#2c3e50",
        cor_secundaria: "#f39c12",
        pais_sede: "🇩🇪 Alemanha",
        marca: Some("Mercedes-AMG"),
        classe: None,
        car_performance_base: 9.0,
        budget_base: 65.0,
        reputacao_base: 68.0,
    },
    TeamTemplate {
        nome: "TR3 Racing",
        nome_curto: "TR3",
        categoria: "gt3",
        cor_primaria: "#003c80",
        cor_secundaria: "#ffd700",
        pais_sede: "🇺🇸 EUA",
        marca: Some("BMW"),
        classe: None,
        car_performance_base: 8.5,
        budget_base: 63.0,
        reputacao_base: 65.0,
    },
    TeamTemplate {
        nome: "AF Corse",
        nome_curto: "AFC",
        categoria: "gt3",
        cor_primaria: "#dc143c",
        cor_secundaria: "#ffffff",
        pais_sede: "🇮🇹 Itália",
        marca: Some("Ferrari"),
        classe: None,
        car_performance_base: 6.5,
        budget_base: 55.0,
        reputacao_base: 57.0,
    },
    TeamTemplate {
        nome: "Cetilar Racing",
        nome_curto: "CTL",
        categoria: "gt3",
        cor_primaria: "#e8c547",
        cor_secundaria: "#1a1a1a",
        pais_sede: "🇮🇹 Itália",
        marca: Some("Ferrari"),
        classe: None,
        car_performance_base: 5.5,
        budget_base: 50.0,
        reputacao_base: 52.0,
    },
    TeamTemplate {
        nome: "EBimotors",
        nome_curto: "EBI",
        categoria: "gt3",
        cor_primaria: "#003c80",
        cor_secundaria: "#c0c0c0",
        pais_sede: "🇮🇹 Itália",
        marca: Some("Porsche"),
        classe: None,
        car_performance_base: 4.5,
        budget_base: 46.0,
        reputacao_base: 48.0,
    },
    TeamTemplate {
        nome: "R8G Esports",
        nome_curto: "R8G",
        categoria: "gt3",
        cor_primaria: "#d63031",
        cor_secundaria: "#ffffff",
        pais_sede: "🇩🇪 Alemanha",
        marca: Some("Audi"),
        classe: None,
        car_performance_base: 6.0,
        budget_base: 52.0,
        reputacao_base: 54.0,
    },
    TeamTemplate {
        nome: "Corvette Racing",
        nome_curto: "CVR",
        categoria: "gt3",
        cor_primaria: "#ffd700",
        cor_secundaria: "#000000",
        pais_sede: "🇺🇸 EUA",
        marca: Some("Chevrolet"),
        classe: None,
        car_performance_base: 2.0,
        budget_base: 39.0,
        reputacao_base: 36.0,
    },
    TeamTemplate {
        nome: "Multimatic Motorsports",
        nome_curto: "MMS",
        categoria: "gt3",
        cor_primaria: "#1a6b3a",
        cor_secundaria: "#ffffff",
        pais_sede: "🇺🇸 EUA",
        marca: Some("Ford"),
        classe: None,
        car_performance_base: 1.0,
        budget_base: 36.0,
        reputacao_base: 33.0,
    },
    TeamTemplate {
        nome: "Acura Team Penske",
        nome_curto: "ATP",
        categoria: "gt3",
        cor_primaria: "#cc0000",
        cor_secundaria: "#ffffff",
        pais_sede: "🇺🇸 EUA",
        marca: Some("Acura"),
        classe: None,
        car_performance_base: -1.0,
        budget_base: 35.0,
        reputacao_base: 31.0,
    },
    TeamTemplate {
        nome: "SunEnergy1 Racing EVO",
        nome_curto: "SEN-E",
        categoria: "endurance",
        cor_primaria: "#ffcc00",
        cor_secundaria: "#1a1a1a",
        pais_sede: "🇺🇸 EUA",
        marca: Some("Mercedes-AMG"),
        classe: Some("gt3"),
        car_performance_base: 15.5,
        budget_base: 85.0,
        reputacao_base: 88.0,
    },
    TeamTemplate {
        nome: "Paul Miller Racing Enduro",
        nome_curto: "PMR-E",
        categoria: "endurance",
        cor_primaria: "#ffd700",
        cor_secundaria: "#1a1a1a",
        pais_sede: "🇺🇸 EUA",
        marca: Some("Lamborghini"),
        classe: Some("gt3"),
        car_performance_base: 14.5,
        budget_base: 82.0,
        reputacao_base: 85.0,
    },
    TeamTemplate {
        nome: "Wright Motorsports 24H",
        nome_curto: "WMS-E",
        categoria: "endurance",
        cor_primaria: "#ff8c00",
        cor_secundaria: "#000000",
        pais_sede: "🇺🇸 EUA",
        marca: Some("Porsche"),
        classe: Some("gt3"),
        car_performance_base: 13.5,
        budget_base: 78.0,
        reputacao_base: 82.0,
    },
    TeamTemplate {
        nome: "AF Corse Endurance",
        nome_curto: "AFC-E",
        categoria: "endurance",
        cor_primaria: "#dc143c",
        cor_secundaria: "#ffffff",
        pais_sede: "🇮🇹 Itália",
        marca: Some("Ferrari"),
        classe: Some("gt3"),
        car_performance_base: 10.0,
        budget_base: 70.0,
        reputacao_base: 73.0,
    },
    TeamTemplate {
        nome: "AKKA ASP Team",
        nome_curto: "AKKA",
        categoria: "endurance",
        cor_primaria: "#2c3e50",
        cor_secundaria: "#c0392b",
        pais_sede: "🇫🇷 França",
        marca: Some("Mercedes-AMG"),
        classe: Some("gt3"),
        car_performance_base: 11.0,
        budget_base: 72.0,
        reputacao_base: 75.0,
    },
    TeamTemplate {
        nome: "GPX Racing",
        nome_curto: "GPX",
        categoria: "endurance",
        cor_primaria: "#1a1a2e",
        cor_secundaria: "#ff8c00",
        pais_sede: "🇫🇷 França",
        marca: Some("Porsche"),
        classe: Some("gt3"),
        car_performance_base: 12.0,
        budget_base: 75.0,
        reputacao_base: 78.0,
    },
    TeamTemplate {
        nome: "Team RLL Endurance",
        nome_curto: "RLL-E",
        categoria: "endurance",
        cor_primaria: "#003c80",
        cor_secundaria: "#ffd700",
        pais_sede: "🇺🇸 EUA",
        marca: Some("BMW"),
        classe: Some("gt4"),
        car_performance_base: 8.5,
        budget_base: 64.0,
        reputacao_base: 59.0,
    },
    TeamTemplate {
        nome: "SRO Endurance Cup",
        nome_curto: "SRO-E",
        categoria: "endurance",
        cor_primaria: "#1c1c1c",
        cor_secundaria: "#f39c12",
        pais_sede: "🇬🇧 Reino Unido",
        marca: Some("Porsche"),
        classe: Some("gt4"),
        car_performance_base: 9.5,
        budget_base: 68.0,
        reputacao_base: 63.0,
    },
    TeamTemplate {
        nome: "HubAuto Endurance",
        nome_curto: "HUB-E",
        categoria: "endurance",
        cor_primaria: "#c8a84b",
        cor_secundaria: "#1c1c1c",
        pais_sede: "🇹🇼 Taiwan",
        marca: Some("Mercedes-AMG"),
        classe: Some("gt4"),
        car_performance_base: 7.0,
        budget_base: 59.0,
        reputacao_base: 54.0,
    },
    TeamTemplate {
        nome: "Heart of Racing 24H",
        nome_curto: "HOR4E",
        categoria: "endurance",
        cor_primaria: "#c0392b",
        cor_secundaria: "#2c3e50",
        pais_sede: "🇺🇸 EUA",
        marca: Some("Aston Martin"),
        classe: Some("gt4"),
        car_performance_base: 10.0,
        budget_base: 70.0,
        reputacao_base: 65.0,
    },
    TeamTemplate {
        nome: "Balfe Endurance",
        nome_curto: "BLF-E",
        categoria: "endurance",
        cor_primaria: "#000080",
        cor_secundaria: "#ff8c00",
        pais_sede: "🇬🇧 Reino Unido",
        marca: Some("McLaren"),
        classe: Some("gt4"),
        car_performance_base: 8.0,
        budget_base: 62.0,
        reputacao_base: 57.0,
    },
    TeamTemplate {
        nome: "GR Racing Endurance",
        nome_curto: "GRR-E",
        categoria: "endurance",
        cor_primaria: "#eb0a1e",
        cor_secundaria: "#ffffff",
        pais_sede: "🇬🇧 Reino Unido",
        marca: Some("Toyota"),
        classe: Some("gt4"),
        car_performance_base: 6.5,
        budget_base: 56.0,
        reputacao_base: 51.0,
    },
    TeamTemplate {
        nome: "United Autosports",
        nome_curto: "UNT",
        categoria: "endurance",
        cor_primaria: "#0000ff",
        cor_secundaria: "#ffffff",
        pais_sede: "🇬🇧 Reino Unido",
        marca: None,
        classe: Some("lmp2"),
        car_performance_base: 16.0,
        budget_base: 90.0,
        reputacao_base: 88.0,
    },
    TeamTemplate {
        nome: "Jota Sport",
        nome_curto: "JOT",
        categoria: "endurance",
        cor_primaria: "#1a1a1a",
        cor_secundaria: "#00bfff",
        pais_sede: "🇬🇧 Reino Unido",
        marca: None,
        classe: Some("lmp2"),
        car_performance_base: 15.0,
        budget_base: 87.0,
        reputacao_base: 85.0,
    },
    TeamTemplate {
        nome: "WRT Racing",
        nome_curto: "WRT",
        categoria: "endurance",
        cor_primaria: "#003c80",
        cor_secundaria: "#ffffff",
        pais_sede: "🇧🇪 Bélgica",
        marca: None,
        classe: Some("lmp2"),
        car_performance_base: 14.5,
        budget_base: 85.0,
        reputacao_base: 83.0,
    },
    TeamTemplate {
        nome: "Prema Powerteam",
        nome_curto: "PRM",
        categoria: "endurance",
        cor_primaria: "#ff0000",
        cor_secundaria: "#ffffff",
        pais_sede: "🇮🇹 Itália",
        marca: None,
        classe: Some("lmp2"),
        car_performance_base: 14.0,
        budget_base: 84.0,
        reputacao_base: 82.0,
    },
    TeamTemplate {
        nome: "Cool Racing",
        nome_curto: "CRL",
        categoria: "endurance",
        cor_primaria: "#00bfff",
        cor_secundaria: "#1a1a1a",
        pais_sede: "🇨🇭 Suíça",
        marca: None,
        classe: Some("lmp2"),
        car_performance_base: 13.5,
        budget_base: 82.0,
        reputacao_base: 80.0,
    },
];

pub fn get_team_templates(category_id: &str) -> Vec<&'static TeamTemplate> {
    TEAMS
        .iter()
        .filter(|team| team.categoria == category_id)
        .collect()
}

pub fn get_teams_for_category(category_id: &str) -> Vec<&'static TeamTemplate> {
    get_team_templates(category_id)
}

pub fn get_all_team_templates() -> &'static [TeamTemplate] {
    TEAMS
}

pub fn count_teams() -> usize {
    TEAMS.len()
}

pub fn get_teams_by_endurance_class(classe: &str) -> Vec<&'static TeamTemplate> {
    TEAMS
        .iter()
        .filter(|team| team.categoria == "endurance" && team.classe == Some(classe))
        .collect()
}

pub fn get_teams_by_brand(marca: &str) -> Vec<&'static TeamTemplate> {
    TEAMS
        .iter()
        .filter(|team| team.marca == Some(marca))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_team_templates_gt3_count() {
        assert_eq!(get_team_templates("gt3").len(), 14);
    }

    #[test]
    fn test_team_templates_production_count() {
        assert_eq!(get_team_templates("production_challenger").len(), 15);
    }
}
